# Auto-generated Pydantic models
# Generated by Knowledge Extraction Agent

```python
from pydantic import BaseModel, Field
from enum import Enum
from typing import Optional

class Classification(str, Enum):
    NATURAL_SCIENCES = "Natural Sciences"
    LIFE_SCIENCES_BIOLOGY = "Life Sciences & Biology"
    MEDICAL_HEALTH_SCIENCES = "Medical & Health Sciences"
    ENGINEERING_TECHNOLOGY = "Engineering & Technology"
    MATHEMATICS_STATISTICS = "Mathematics & Statistics"
    SOCIAL_SCIENCES = "Social Sciences"
    HUMANITIES_ARTS = "Humanities & Arts"
    ENVIRONMENTAL_EARTH_SCIENCES = "Environmental & Earth Sciences"
    AGRICULTURAL_FOOD_SCIENCES = "Agricultural & Food Sciences"
    INFORMATION_COMPUTER_SCIENCES = "Information & Computer Sciences"

class ResearchDocumentAnalysisInfo(BaseModel):
    title: str = Field(..., description="paper title")
    authors: str = Field(..., description="names of all authors separated by comma")
    vol: str = Field(..., description="journal's volume number")
    issue: str = Field(..., description="issue number")
    year: str = Field(..., description="publication year")
    classification: Classification = Field(..., description="the main, high-level field the paper can be classified into.")
    abstract: str = Field(..., description="paper's abstract")
```