"""
Auto-generated Extraction Prompt with Embedded Models
Generated by Knowledge Extraction Agent
This file contains a complete, self-contained extraction prompt system.
"""

EXTRACTION_PROMPT = """
TASK: Research paper data extraction

EXTRACTION TASK:
Knowledge extraction from research papers

EMBEDDED PYDANTIC MODELS:
```python
```python
from pydantic import BaseModel, Field
from enum import Enum
from typing import Optional

class Classification(str, Enum):
    NATURAL_SCIENCES = "Natural Sciences"
    LIFE_SCIENCES_BIOLOGY = "Life Sciences & Biology"
    MEDICAL_HEALTH_SCIENCES = "Medical & Health Sciences"
    ENGINEERING_TECHNOLOGY = "Engineering & Technology"
    MATHEMATICS_STATISTICS = "Mathematics & Statistics"
    SOCIAL_SCIENCES = "Social Sciences"
    HUMANITIES_ARTS = "Humanities & Arts"
    ENVIRONMENTAL_EARTH_SCIENCES = "Environmental & Earth Sciences"
    AGRICULTURAL_FOOD_SCIENCES = "Agricultural & Food Sciences"
    INFORMATION_COMPUTER_SCIENCES = "Information & Computer Sciences"

class ResearchDocumentAnalysisInfo(BaseModel):
    title: str = Field(..., description="paper title")
    authors: str = Field(..., description="names of all authors separated by comma")
    vol: str = Field(..., description="journal's volume number")
    issue: str = Field(..., description="issue number")
    year: str = Field(..., description="publication year")
    classification: Classification = Field(..., description="the main, high-level field the paper can be classified into.")
    abstract: str = Field(..., description="paper's abstract")
```
```

CRITICAL EXTRACTION RULES:
1. ACCURACY & VERIFICATION:
   - Extract information ONLY from the provided text
   - Never fabricate, infer, or guess any information
   - Use 'n/a' for any fields where information is not explicitly stated
   - Verify all extracted data against the source text
   - Maintain exact values, dates, and numerical figures as written

2. DATA HANDLING:
   - For dates: Use DD-MM-YYYY format when possible
   - For numbers: Preserve original precision and units
   - For text: Maintain original spelling and capitalization
   - For lists: Extract all relevant items, remove duplicates
   - For enums: Choose ONLY from the specified options
   - For the extracted fields whose length exceeds 30 words, summarize their text into less than 30 words comprising very brief key phrases separated by semi-colon.

3. FIELD VALIDATION:
   - Enum fields must match one of the specified values exactly
   - List fields should contain valid, non-empty items
   - Numerical fields should be valid numbers in correct format

4. QUALITY ASSURANCE:
   - Double-check all extracted information against source
   - Ensure no information is duplicated across fields
   - Verify that field types match the expected data types
   - Confirm that all required fields are addressed
   - Validate that enum selections are from available options


OUTPUT FORMAT:
Return the extracted information as a JSON object that exactly matches the ResearchDocumentAnalysisInfo structure shown above.

CRITICAL: All JSON field names MUST be in snake_case format (lowercase with underscores) to match the model exactly.
For example: "due_date", "bank_name", "car_type" - NOT "Due date", "bank name", "car type"

Example output structure:
```json
{
  "field_name_1": "extracted_value_or_n/a",
  "field_name_2": ["list", "of", "values"],
  "field_name_3": "enum_option_or_n/a"
}
```

VALIDATION CHECKLIST:
Before returning your response, verify:
- All required fields are populated or marked 'n/a'
- All enum fields contain valid options only
- All numerical fields contain valid numbers
- All date fields follow proper format
- No information is fabricated or inferred
- JSON structure matches the model exactly
- Field names match the model exactly
- Data types are appropriate for each field

FINAL INSTRUCTIONS:
- Process the document systematically
- Extract information field by field as specified above
- Maintain accuracy over completeness
- When in doubt, use 'n/a' rather than guessing
- Return only the JSON object with extracted data
- Ensure the output can be parsed as valid JSON
"""

def get_extraction_prompt():
    """Return the complete extraction prompt with embedded models"""
    return EXTRACTION_PROMPT
